//
// Created by grigoriy.senchenok on 26.04.2022.
//

#ifndef TRANSPORTEQUATION_DGSOLVER1DPARAMS_H
#define TRANSPORTEQUATION_DGSOLVER1DPARAMS_H


class DGSolver1DParams {

};


#endif //TRANSPORTEQUATION_DGSOLVER1DPARAMS_H
