//
// Created by grigoriy.senchenok on 21.02.2022.
//

#ifndef TRANSPORTEQUATION_DIGITALGEOMETRYTESTS1D_H
#define TRANSPORTEQUATION_DIGITALGEOMETRYTESTS1D_H

void StripSinMoveTest();

#endif //TRANSPORTEQUATION_DIGITALGEOMETRYTESTS1D_H
