//
// Created by grigoriy.senchenok on 21.02.2022.
//

#ifndef TRANSPORTEQUATION_EULEREQUATION2DTESTS_H
#define TRANSPORTEQUATION_EULEREQUATION2DTESTS_H

void ParabolicCenterTest();

#endif //TRANSPORTEQUATION_EULEREQUATION2DTESTS_H
