//
// Created by grigoriy.senchenok on 08.02.2022.
//

#ifndef TRANSPORTEQUATION_TRANSPORTEQUATION2DTESTS_H
#define TRANSPORTEQUATION_TRANSPORTEQUATION2DTESTS_H

void Solve2DRectMovementTest();

#endif //TRANSPORTEQUATION_TRANSPORTEQUATION2DTESTS_H
