//
// Created by gsench on 02.05.22.
//

#ifndef TRANSPORTEQUATION_EESOLVER2DOUTPUT_H
#define TRANSPORTEQUATION_EESOLVER2DOUTPUT_H


class EESolver2DOutput {
//TODO
};


#endif //TRANSPORTEQUATION_EESOLVER2DOUTPUT_H
